spring:
  profiles:
    active:
      - @buildEnvironment@
  datasource:
    username: @db.username@
    password: @db.password@
    url: jdbc:mysql://localhost:3306/shop_project?serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
